#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C28_float{1,0,20.2,5
#
app.x28FP: package/cfg/app.x28FP.mak

clean::
	-$(RM) package/cfg/app.x28FP.mak
